### ISSUE TITLE
Problems with escaping whitespace in 'write'

### ISSUE THREAD

**Issue by maltesander** [adamcrume/java-properties#5]
I am using this library and stumbled over a problem with (escaping) whitespaces:

If you have a map like map("key", "value with space") it will be escaped and written to "key=value\ with \space". Check https://github.com/adamcrume/java-properties/blob/002c8e5bd16bead924f488a5f1b1a6ee0fb09e47/src/lib.rs#L630

I am not sure if this is a bug or a feature, but several Java products cannot work with that (e.g. Apache NiFi).

The real example was "5 mins" which was written to "5\ mins".

For what reason are you escaping whitespaces? Can you elaborate or have a look?

Thanks in advance,
Malte

**Comment by adamcrume** [comment]
It looks like this library is escaping slightly more aggressively than the Java implementation.  For reference, the Java code

```java
Properties p = new Properties();
p.setProperty(" key with space ", " value with space ");
StringWriter out = new StringWriter();
p.store(out, "");
System.out.println(out);
```

prints out

```
#
#Mon Aug 09 21:54:33 PDT 2021
\ key\ with\ space\ =\ value with space 
```

However, the extra escaping output by this library is readable by Java:

```java
Properties p = new Properties();
p.load(new StringReader("\\ key\\ with\\ space\\ =\\ value\\ with\\ space\\ "));
System.out.println(p);
```

prints out

```
{ key with space = value with space }
```

The Javadoc on Properties.load says

> The method does not treat a backslash character, \\, before a non-valid escape character as an error; the backslash is silently dropped. For example, in a Java string the sequence "\z" would cause a compile time error. In contrast, this method silently drops the backslash. Therefore, this method treats the two character sequence "\b" as equivalent to the single character 'b'. 

which means that the extra backslashes before spaces should be ignored anyway.  It sounds like Apache NiFi has a bug if it is unable to read that.

It should be relatively easy to change this so the output is more easily read by buggy libraries.

**Comment by maltesander** [comment]
Hi Adam,

yes thank you for the quick answer, i tested with the "native" java properties as well. I never saw that in any config file.

I will investigate in NiFi then a little bit more.

Ill close this one, have a good day :)
